# PHP Web Server
web:
  # Build the Drupal 8 image
  # https://hub.docker.com/r/_/drupal/
  image: drupal:8
  # Environment variables
  environment:
    # Drupal settings
    DRUPAL_PROFILE: standard
    DRUPAL_SITE_NAME: Drupal
    DRUPAL_USER: admin
    DRUPAL_PASS: admin
    DRUPAL_DBURL: mysql://drupal:drupal@database:3306/drupal
  ports:
    # Host machine's port 8000 will map to Drupal's port 80
    - "8000:80"
  volumes:
    # Drupal should live in the "drupal" directory
    - ./drupal:/app
  links:
    - database:database
  command: php -S 0.0.0.0:80 -t /app
  working_dir: /app
  restart: always

# MySQL Server
database:
  image: mariadb:10
  environment:
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
    MYSQL_DATABASE: drupal
    MYSQL_ROOT_PASSWORD: ''
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  expose:
    - "3306"
  restart: always
